//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en_US() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("API.Resources.en-US", typeof(en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Null exception.
        /// </summary>
        internal static string ArgumentNullExceptionResponseMessage {
            get {
                return ResourceManager.GetString("ArgumentNullExceptionResponseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something out of range.
        /// </summary>
        internal static string ArgumentOutOfRangeExceptionResponseMessage {
            get {
                return ResourceManager.GetString("ArgumentOutOfRangeExceptionResponseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something happened while delete category.
        /// </summary>
        internal static string CategoryDeleteExceptionResponseMessage {
            get {
                return ResourceManager.GetString("CategoryDeleteExceptionResponseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No categories found with this ID.
        /// </summary>
        internal static string CategoryNotFoundExceptionMessage {
            get {
                return ResourceManager.GetString("CategoryNotFoundExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something wrong.
        /// </summary>
        internal static string ExceptionResponseMessage {
            get {
                return ResourceManager.GetString("ExceptionResponseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The category financial type is incorrect.
        /// </summary>
        internal static string FinancialTypeExceptionResponceMessage {
            get {
                return ResourceManager.GetString("FinancialTypeExceptionResponceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something not found.
        /// </summary>
        internal static string KeyNotFoundExceptionResponseMessage {
            get {
                return ResourceManager.GetString("KeyNotFoundExceptionResponseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something happened during authentication, please try again.
        /// </summary>
        internal static string NotAuthenticatedExceptionResponseMessage {
            get {
                return ResourceManager.GetString("NotAuthenticatedExceptionResponseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don`t have permission for this action.
        /// </summary>
        internal static string NotAuthorizedExceptionResponseMessage {
            get {
                return ResourceManager.GetString("NotAuthorizedExceptionResponseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something return null.
        /// </summary>
        internal static string ObjectNotFoundExceptionResponseMessage {
            get {
                return ResourceManager.GetString("ObjectNotFoundExceptionResponseMessage", resourceCulture);
            }
        }
    }
}
